name: pycwb-0.30.1
channels:
  - conda-forge
  - igwn
dependencies:
  - python=3.10
  - root=6.26.10 
  - healpix_cxx=3.81 
  - nds2-client 
  - python-nds2-client 
  - lalsuite 
  - setuptools_scm 
  - cmake 
  - pkg-config
  - pip
  - gwpy
  - matplotlib<3.8
  - pip:
    - pycwb==0.30.1
    - wdm-wavelet
    - burst-waveform